const root=document.getElementById('app');
const view=new URLSearchParams(location.search).get('view')||'main';
let state,tab='home',toastTimer,resultExpanded=false;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
function toast(message,error=false){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;document.body.append(el);clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.remove(),6000);}
async function action(fn){try{return await fn();}catch(e){toast(e.message.replace(/^Error invoking remote method '[^']+': (Error: )?/,''),true);}}
function options(selected){return state.languages.map(l=>`<option ${l===selected?'selected':''}>${esc(l)}</option>`).join('');}
function records(items){return items.map(r=>`<article class="record"><div class="record-meta"><span>${esc(r.app)} · ${esc(r.target)}</span><span>${esc(new Date(r.createdAt).toLocaleString())}</span></div>${r.imagePath?`<img class="capture-preview" src="${esc('file:///'+r.imagePath.replace(/\\/g,'/'))}" alt="Captured screen region">`:''}<p class="original">${esc(r.source||'No source text recognized.')}</p>${r.error?`<p class="history-error">${esc(r.error)}</p>`:`<p>${esc(r.translation)}</p>`}<button data-copy="${esc(r.id)}" ${r.translation?'':'disabled'}>Copy translation</button></article>`).join('');}
function renderMain(){
  document.body.className='';
  root.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="mark">L</span> lens<span class="muted" style="display:none">translate</span></div><nav class="nav"><button data-tab="home" class="${tab==='home'?'active':''}">◎ &nbsp; Overview</button><button data-tab="history" class="${tab==='history'?'active':''}">↺ &nbsp; Translation history</button><button data-tab="settings" class="${tab==='settings'?'active':''}">⚙ &nbsp; Settings</button></nav><div class="sidebar-bottom"><span class="dot"></span> Ready when you are<br>Screen translation, in place.<br><br>v0.1 · Windows</div></aside><main class="content" id="content"></main></div>`;
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderMain();});
  const s=state.settings;
  if(tab==='home')$('content').innerHTML=`<div class="eyebrow">A little clarity, anywhere</div><h1>Your screen. Your language.</h1><p class="intro">Understand what’s in front of you. Translate text from apps, images, and documents without leaving the moment.</p><section class="hero"><div class="eyebrow">Screen translator</div><h2 style="margin-top:16px">Point. Capture. Understand.</h2><p>Click a paragraph or draw a box around any text. Your translation appears right beside it.</p><div class="hero-bottom"><button class="primary" id="capture">＋ &nbsp; Translate screen</button><span>${s.hotkey.split('+').map(k=>`<span class="key">${esc(k)}</span>`).join(' + ')}</span></div></section><div class="grid"><section class="card"><div class="number">01 / LANGUAGE</div><h2>${esc(s.source)} → ${esc(s.target)}</h2><p>The source language helps local OCR read your screen accurately. Change it in Settings.</p></section><section class="card"><div class="number">02 / CONTEXT</div><h2>${s.context?'Understands the conversation':'Just the text'}</h2><p>${s.context?'Recent translations from the same app and window help keep terminology consistent.':'App context is off. Only captured text and your glossary are used.'}</p></section></div><div class="section-head"><h2>Recent translations</h2><span class="status">${state.hasKey?'API key connected':'API key needed'}</span></div>${state.history.length?records(state.history.slice(0,2)):'<div class="empty">A fresh perspective starts with your first capture.</div>'}<p class="footnote">OCR happens on this device. Extracted text is sent to OpenAI for translation. Use borderless fullscreen for games; protected screens may not be capturable.</p>`;
  if(tab==='history')$('content').innerHTML=`<div class="eyebrow">Your words, remembered</div><h1>Translation history</h1><p class="intro">The latest 200 translations, stored on this device.</p><div class="section-head"><input id="search" placeholder="Search source, translation, or app…" aria-label="Search history"><button id="clear">Clear history</button></div><div id="history-list">${state.history.length?records(state.history):'<div class="empty">No translations yet.</div>'}</div><p class="footnote">History is saved as local text. Turn it off in Settings for sensitive content.</p>`;
  if(tab==='settings')$('content').innerHTML=`<div class="eyebrow">Make yourself understood</div><h1>Settings</h1><p class="intro">Choose your languages, connect OpenAI, and decide what Lens remembers.</p><form id="settings-form"><section class="card"><h2>Languages & activation</h2><div class="row"><label class="field"><span>Read text in (OCR language)</span><select id="source">${options(s.source)}</select></label><label class="field"><span>Translate into</span><select id="target">${options(s.target)}</select></label></div><label class="field"><span>Global shortcut</span><input id="hotkey" value="${esc(s.hotkey)}"><small>Use modifiers and a letter, for example Alt+Shift+T.</small></label><h2>OpenAI connection</h2><label class="field"><span>API key ${state.hasKey?'· saved securely':'· required'}</span><input id="apiKey" type="password" autocomplete="off" placeholder="${state.hasKey?'Leave blank to keep your saved key':'sk-…'}"><small>Encrypted with Windows secure storage. Never sent to the app interface.</small></label><label class="field"><span>Model</span><input id="model" value="${esc(s.model)}"><small>Use a text model available to your OpenAI API account. API usage is billed separately.</small></label><label class="toggle"><input type="checkbox" id="removeKey">Remove saved API key on save</label><label class="toggle"><input type="checkbox" id="context" ${s.context?'checked':''}>Use app name, window title, and recent same-window translations as context</label><label class="toggle"><input type="checkbox" id="history" ${s.history?'checked':''}>Save translation history on this device</label><p class="footnote">Disabling history stops new records. Clear existing records in Translation history. Context may include document titles; disable it when translating sensitive material.</p><label class="field"><span>Terminology glossary</span><textarea id="glossary" maxlength="4000" placeholder="Example: translate ‘workspace’ as ‘espace de travail’">${esc(s.glossary)}</textarea></label><label class="field"><span>Blocked apps (process names, one per line)</span><textarea id="blockedApps" maxlength="2000" placeholder="KeePass\n1Password">${esc(s.blockedApps)}</textarea></label><div class="actions"><button class="primary" type="submit">Save settings</button><span class="muted" id="saved"></span></div></section></form>`;
  $('capture')?.addEventListener('click',()=>action(()=>window.lens.capture()));
  if(tab==='home')document.querySelector('.hero p').textContent='Hold Ctrl and left-drag over any text for a quick capture. Use Alt + Shift + T when a game does not expose mouse input.';
  $('search')?.addEventListener('input',e=>{const query=e.target.value.toLowerCase();$('history-list').innerHTML=records(state.history.filter(r=>[r.source,r.translation,r.app].some(v=>v.toLowerCase().includes(query))));bindCopy();});
  $('clear')?.addEventListener('click',()=>action(async()=>{if(!confirm('Delete all local translation history?'))return;await window.lens.clear();state.history=[];renderMain();}));
  $('settings-form')?.addEventListener('submit',e=>{e.preventDefault();action(async()=>{const settings={source:$('source').value,target:$('target').value,hotkey:$('hotkey').value.trim(),model:$('model').value.trim(),context:$('context').checked,history:$('history').checked,glossary:$('glossary').value,blockedApps:$('blockedApps').value};const result=await window.lens.save({settings,apiKey:$('apiKey').value,removeKey:$('removeKey').checked});state.settings=settings;state.hasKey=result.hasKey;renderMain();toast('Settings saved. Your shortcut is ready.');});});bindCopy();
}
function bindCopy(){document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>action(async()=>{const r=state.history.find(r=>r.id===b.dataset.copy);await window.lens.copy(r.translation);toast('Copied translation');}));}
function renderSelect(){
  document.body.className='select-view';root.innerHTML='<img class="screen-image" id="screen" alt="Captured screen"><div class="shade" id="shade"></div><div class="selection-box" id="box"></div><div class="select-tip">Click a paragraph or drag around text &nbsp; · &nbsp; Esc to cancel</div>';
  $('screen').src=state.capture.image;let start=null,submitted=false;
  window.onpointerdown=e=>{if(e.button!==0||submitted)return;start={x:e.clientX,y:e.clientY};$('shade').style.display='none';};
  window.onpointermove=e=>{if(!start)return;Object.assign($('box').style,{display:'block',left:Math.min(start.x,e.clientX)+'px',top:Math.min(start.y,e.clientY)+'px',width:Math.abs(e.clientX-start.x)+'px',height:Math.abs(e.clientY-start.y)+'px'});};
  window.onpointerup=e=>{if(!start||submitted)return;submitted=true;const width=Math.abs(e.clientX-start.x),height=Math.abs(e.clientY-start.y);action(()=>window.lens.select({x:Math.min(start.x,e.clientX),y:Math.min(start.y,e.clientY),width,height,click:width<8&&height<8,viewportWidth:window.innerWidth,viewportHeight:window.innerHeight}));start=null;};
}
function renderDrag(){document.body.className='drag-view';root.innerHTML='<div class="drag-highlight" id="drag-highlight"></div>';}
function renderResult(r){
  if(!r.source&&r.status==='loading')resultExpanded=false;
  if(!resultExpanded){
    document.body.className='result-view compact-result';
    const text=r.status==='done'?r.translation:r.status==='error'?r.error:r.message;
    root.innerHTML=`<section class="result-card compact-card"><div class="compact-text" dir="auto">${esc(text||'Reading your screen…')}</div><button id="expand-result" aria-label="Show details">⌄</button></section>`;
    const size=()=>{const length=(text||'').length,width=Math.max(180,Math.min(420,length*9+70)),textBox=document.querySelector('.compact-text');textBox.style.width=(width-54)+'px';const height=Math.max(70,Math.min(360,textBox.scrollHeight+38));window.lens.expand({expanded:false,width,height}).catch(()=>{});};requestAnimationFrame(size);
    $('expand-result').onclick=()=>action(async()=>{resultExpanded=true;await window.lens.expand({expanded:true});renderResult(r);});
    return;
  }
  document.body.className='result-view';
  root.innerHTML=`<section class="result-card"><header class="result-top"><span class="result-title">LENS &nbsp; / &nbsp; ${esc(r.target||'TRANSLATE')}</span><button id="dismiss" aria-label="Dismiss">×</button></header><div class="result-body"><div class="result-app">${esc(r.app||'Screen translation')}${r.cached?' · cached':''}</div>${r.status==='loading'?`<div class="loading">${esc(r.message)}</div>`:''}${r.status==='error'?`<div class="error-text">${esc(r.error)}</div>`:''}${r.status==='done'?`<div class="translation" dir="auto">${esc(r.translation)}</div>`:''}${r.confidence<65?'<small>Low OCR confidence. Review the source text before relying on this translation.</small>':''}${r.source?`<details ${r.status==='error'?'open':''}><summary>Source text · edit & retry</summary><textarea id="source-edit" aria-label="Recognized source text" dir="auto">${esc(r.source)}</textarea><button id="retry" ${r.status==='loading'?'disabled':''}>Translate edited text</button></details>`:''}${r.clickThrough?'<small>Click-through on. Press Alt+Shift+X to restore controls.</small>':''}</div><footer class="result-footer"><button id="copy-result" ${r.status==='done'?'':'disabled'}>Copy</button><button id="new-capture">New capture</button><button id="open-settings">Settings</button><button id="passthrough">Click-through</button></footer></section>`;
  $('dismiss').onclick=()=>action(async()=>{resultExpanded=false;await window.lens.expand({expanded:false});await window.lens.dismiss();});
  $('copy-result').onclick=()=>action(async()=>{await window.lens.copy(r.translation);toast('Copied');});
  $('new-capture').onclick=()=>action(async()=>{resultExpanded=false;await window.lens.capture();});
  $('open-settings').onclick=()=>action(()=>window.lens.settings());
  $('passthrough').onclick=()=>action(()=>window.lens.passthrough(true));
  $('retry')?.addEventListener('click',()=>action(()=>window.lens.retry($('source-edit').value)));
}
window.onkeydown=e=>{if(e.key==='Escape'&&view!=='main')window.lens.dismiss();};
window.lens.onUpdate(data=>{
  if(data.type==='result'&&view==='result')renderResult(data);
  if(data.type==='drag'&&view==='drag'){const box=$('drag-highlight');Object.assign(box.style,{left:data.x+'px',top:data.y+'px',width:data.width+'px',height:data.height+'px',display:data.width>2&&data.height>2?'block':'none'});}
  if(data.type==='error'&&view==='main')toast(data.error,true);
  if(data.type==='history'&&state&&view==='main'){state.history=data.history;if(tab!=='settings')renderMain();}
});
window.lens.state().then(value=>{state=value;if(view==='select')renderSelect();else if(view==='result')renderResult(state.result);else if(view==='drag')renderDrag();else renderMain();}).catch(error=>{root.textContent='Unable to initialize Lens: '+error.message;});
