const root=document.getElementById('app');
const view=new URLSearchParams(location.search).get('view')||'main';
let state,tab='home',toastTimer,resultExpanded=false;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
function toast(message,error=false){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;document.body.append(el);clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.remove(),6000);}
async function action(fn){try{return await fn();}catch(e){toast(e.message.replace(/^Error invoking remote method '[^']+': (Error: )?/,''),true);}}
function options(selected){return state.languages.map(l=>`<option ${l===selected?'selected':''}>${esc(l)}</option>`).join('');}
function records(items){return items.map(r=>`<article class="record"><div class="record-meta"><span>${esc(r.app)} · ${esc(r.target)}</span><span>${esc(new Date(r.createdAt).toLocaleString())}</span></div>${r.imagePath?`<img class="capture-preview" src="${esc('file:///'+r.imagePath.replace(/\\/g,'/'))}" alt="Captured screen region">`:''}<p class="original">${esc(r.source||'No source text recognized.')}</p>${r.error?`<p class="history-error">${esc(r.error)}</p>`:`<p>${esc(r.translation)}</p>`}<button data-copy="${esc(r.id)}" ${r.translation?'':'disabled'}>Copy translation</button></article>`).join('');}
function icon(name){
  const paths={home:'<rect x="3" y="3" width="18" height="18" rx="4"/><path d="M8 3v18"/>',history:'<path d="M3 11a9 9 0 1 1 2.6 7.4M3 4v7h7M12 7v5l3 2"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',capture:'<path d="M8 3H5a2 2 0 0 0-2 2v3m13-5h3a2 2 0 0 1 2 2v3M3 16v3a2 2 0 0 0 2 2h3m13-5v3a2 2 0 0 1-2 2h-3M8 12h8m-4-4v8"/>',language:'<path d="M3 5h12M9 3v2m4 0c-1 6-4 9-9 11m1-8c1 3 4 6 7 7m1 6 4-10 4 10m-6-4h4"/>',context:'<path d="M21 11a8 8 0 0 1-8 8H7l-4 3V11a8 8 0 0 1 8-8h2a8 8 0 0 1 8 8Z"/><path d="M7 9h10M7 13h6"/>'};
  return `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.capture}</svg>`;
}
function emptyHistory(){return `<div class="empty">${icon('history')}<strong>No translations yet</strong><p>Capture text on your screen to start. Your translations will appear here.</p></div>`;}
function renderMain(){
  document.body.className='';
  const pageTitle={home:'Overview',history:'Translation history',settings:'Settings'}[tab];
  root.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="mark">${icon('capture')}</span><span class="brand-name">Lens</span></div><nav class="nav" aria-label="Main navigation">${[['home','Overview'],['history','Translation history'],['settings','Settings']].map(([key,label])=>`<button data-tab="${key}" aria-label="${label}" ${tab===key?'aria-current="page"':''} class="${tab===key?'active':''}">${icon(key)}<span class="nav-label">${label}</span></button>`).join('')}</nav><div class="sidebar-bottom">${state.hasKey?'<span class="dot"></span>Ready to translate':'Connect an API key in Settings'}<p>Lens Translate · Windows</p></div></aside><div class="workspace"><header class="workspace-header">${pageTitle}<span>Screen translation, in place</span></header><main class="content" id="content"></main></div></div>`;
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderMain();});
  const s=state.settings;
  if(tab==='home')$('content').innerHTML=`<h1>What would you like to translate?</h1><p class="intro">Capture text from any app and read it in your language.</p><section class="hero"><h2>Translate your screen</h2><p>Hold Ctrl and drag over text to capture a region. You can also use the button or shortcut below.</p><div class="hero-bottom"><span class="shortcut" aria-label="Keyboard shortcut">${s.hotkey.split('+').map(k=>`<kbd class="key">${esc(k)}</kbd>`).join('<span>+</span>')}</span><button class="primary" id="capture">${icon('capture')}Translate screen</button></div></section><div class="grid"><section class="card"><div class="number">${icon('language')}Languages</div><h2>${esc(s.source)} → ${esc(s.target)}</h2><p>Change your source and target in Settings.</p></section><section class="card"><div class="number">${icon('context')}App context</div><h2>${s.context?'Context enabled':'Context disabled'}</h2><p>${s.context?'Uses recent translations from the same app and window.':'Translates with your captured text and glossary.'}</p></section></div><div class="section-head"><h2>Recent translations</h2><button class="text-button" id="view-history">View all</button></div>${state.history.length?records(state.history.slice(0,2)):emptyHistory()}<p class="footnote">Text recognition runs on your device. Extracted text is sent to OpenAI for translation.</p>`;
  if(tab==='history')$('content').innerHTML=`<h1>Translation history</h1><p class="intro">The latest 200 translations, stored on this device.</p><div class="section-head"><input id="search" placeholder="Search source, translation, or app…" aria-label="Search history"><button id="clear">Clear history</button></div><div id="history-list">${state.history.length?records(state.history):emptyHistory()}</div><p class="footnote">History and captured images are saved on this device. Turn it off in Settings for sensitive content.</p>`;
  if(tab==='settings')$('content').innerHTML=`<h1>Settings</h1><p class="intro">Choose your languages, connect OpenAI, and decide what Lens remembers.</p><form id="settings-form"><section class="settings-section"><h2>Languages & activation</h2><div class="row"><label class="field"><span>Read text in (OCR language)</span><select id="source">${options(s.source)}</select></label><label class="field"><span>Translate into</span><select id="target">${options(s.target)}</select></label></div><label class="field"><span>Global shortcut</span><input id="hotkey" value="${esc(s.hotkey)}"><small>Use modifiers and a letter, for example Alt+Shift+T.</small></label></section><section class="settings-section"><h2>OpenAI connection</h2><label class="field"><span>API key ${state.hasKey?'· saved securely':'· required'}</span><input id="apiKey" type="password" autocomplete="off" placeholder="${state.hasKey?'Leave blank to keep your saved key':'sk-…'}"><small>Encrypted with Windows secure storage. Never sent to the app interface.</small></label><label class="field"><span>Model</span><input id="model" value="${esc(s.model)}"><small>Use a text model available to your OpenAI API account. API usage is billed separately.</small></label><label class="toggle"><input type="checkbox" id="removeKey">Remove saved API key on save</label></section><section class="settings-section"><h2>Context & history</h2><label class="toggle"><input type="checkbox" id="context" ${s.context?'checked':''}>Use app name, window title, and recent same-window translations as context</label><label class="toggle"><input type="checkbox" id="history" ${s.history?'checked':''}>Save translation history on this device</label><p class="footnote">Disabling history stops new records. Clear existing records in Translation history. Context may include document titles; disable it when translating sensitive material.</p></section><section class="settings-section"><h2>Translation preferences</h2><label class="field"><span>Terminology glossary</span><textarea id="glossary" maxlength="4000" placeholder="Example: translate ‘workspace’ as ‘espace de travail’">${esc(s.glossary)}</textarea></label><label class="field"><span>Blocked apps (process names, one per line)</span><textarea id="blockedApps" maxlength="2000" placeholder="KeePass\n1Password">${esc(s.blockedApps)}</textarea></label></section><div class="actions"><button class="primary" type="submit">Save settings</button><span class="muted" id="saved"></span></div></form>`;
  $('capture')?.addEventListener('click',()=>action(()=>window.lens.capture()));
  $('view-history')?.addEventListener('click',()=>{tab='history';renderMain();});
  $('search')?.addEventListener('input',e=>{const query=e.target.value.toLowerCase();$('history-list').innerHTML=records(state.history.filter(r=>[r.source,r.translation,r.app].some(v=>String(v||'').toLowerCase().includes(query))))||'<div class="empty">No translations match your search.</div>';bindCopy();});
  $('clear')?.addEventListener('click',()=>action(async()=>{if(!confirm('Delete all local translation history?'))return;await window.lens.clear();state.history=[];renderMain();}));
  $('settings-form')?.addEventListener('submit',e=>{e.preventDefault();action(async()=>{const settings={source:$('source').value,target:$('target').value,hotkey:$('hotkey').value.trim(),model:$('model').value.trim(),context:$('context').checked,history:$('history').checked,glossary:$('glossary').value,blockedApps:$('blockedApps').value};const result=await window.lens.save({settings,apiKey:$('apiKey').value,removeKey:$('removeKey').checked});state.settings=settings;state.hasKey=result.hasKey;renderMain();toast('Settings saved. Your shortcut is ready.');});});bindCopy();
}
function bindCopy(){document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>action(async()=>{const r=state.history.find(r=>r.id===b.dataset.copy);await window.lens.copy(r.translation);toast('Copied translation');}));}
function renderSelect(){
  document.body.className='select-view';root.innerHTML='<img class="screen-image" id="screen" alt="Captured screen"><div class="shade" id="shade"></div><div class="selection-box" id="box"></div><div class="select-tip">Click a paragraph or drag around text &nbsp; · &nbsp; Esc to cancel</div>';
  $('screen').src=state.capture.image;let start=null,submitted=false;
  window.onpointerdown=e=>{if(e.button!==0||submitted)return;start={x:e.clientX,y:e.clientY};$('shade').style.display='none';};
  window.onpointermove=e=>{if(!start)return;Object.assign($('box').style,{display:'block',left:Math.min(start.x,e.clientX)+'px',top:Math.min(start.y,e.clientY)+'px',width:Math.abs(e.clientX-start.x)+'px',height:Math.abs(e.clientY-start.y)+'px'});};
  window.onpointerup=e=>{if(!start||submitted)return;submitted=true;const width=Math.abs(e.clientX-start.x),height=Math.abs(e.clientY-start.y);action(()=>window.lens.select({x:Math.min(start.x,e.clientX),y:Math.min(start.y,e.clientY),width,height,click:width<8&&height<8,viewportWidth:window.innerWidth,viewportHeight:window.innerHeight}));start=null;};
}
function renderDrag(){document.body.className='drag-view';root.innerHTML='<div class="drag-highlight" id="drag-highlight"></div>';}
function renderResult(r){
  if(!r.source&&r.status==='loading')resultExpanded=false;
  if(!resultExpanded){
    document.body.className='result-view compact-result';
    const text=r.status==='done'?r.translation:r.status==='error'?r.error:r.message;
    root.innerHTML=`<section class="result-card compact-card"><div class="compact-text" dir="auto">${esc(text||'Reading your screen…')}</div><button id="expand-result" aria-label="Show details">⌄</button></section>`;
    const size=()=>{const length=(text||'').length,width=Math.max(180,Math.min(420,length*9+70)),textBox=document.querySelector('.compact-text');textBox.style.width=(width-54)+'px';const height=Math.max(70,Math.min(360,textBox.scrollHeight+38));window.lens.expand({expanded:false,width,height}).catch(()=>{});};requestAnimationFrame(size);
    $('expand-result').onclick=()=>action(async()=>{resultExpanded=true;await window.lens.expand({expanded:true});renderResult(r);});
    return;
  }
  document.body.className='result-view';
  root.innerHTML=`<section class="result-card"><header class="result-top"><span class="result-title">LENS &nbsp; / &nbsp; ${esc(r.target||'TRANSLATE')}</span><button id="dismiss" aria-label="Dismiss">×</button></header><div class="result-body"><div class="result-app">${esc(r.app||'Screen translation')}${r.cached?' · cached':''}</div>${r.status==='loading'?`<div class="loading">${esc(r.message)}</div>`:''}${r.status==='error'?`<div class="error-text">${esc(r.error)}</div>`:''}${r.status==='done'?`<div class="translation" dir="auto">${esc(r.translation)}</div>`:''}${r.confidence<65?'<small>Low OCR confidence. Review the source text before relying on this translation.</small>':''}${r.source?`<details ${r.status==='error'?'open':''}><summary>Source text · edit & retry</summary><textarea id="source-edit" aria-label="Recognized source text" dir="auto">${esc(r.source)}</textarea><button id="retry" ${r.status==='loading'?'disabled':''}>Translate edited text</button></details>`:''}${r.clickThrough?'<small>Click-through on. Press Alt+Shift+X to restore controls.</small>':''}</div><footer class="result-footer"><button id="copy-result" ${r.status==='done'?'':'disabled'}>Copy</button><button id="new-capture">New capture</button><button id="open-settings">Settings</button><button id="passthrough">Click-through</button></footer></section>`;
  $('dismiss').onclick=()=>action(async()=>{resultExpanded=false;await window.lens.expand({expanded:false});await window.lens.dismiss();});
  $('copy-result').onclick=()=>action(async()=>{await window.lens.copy(r.translation);toast('Copied');});
  $('new-capture').onclick=()=>action(async()=>{resultExpanded=false;await window.lens.capture();});
  $('open-settings').onclick=()=>action(()=>window.lens.settings());
  $('passthrough').onclick=()=>action(()=>window.lens.passthrough(true));
  $('retry')?.addEventListener('click',()=>action(()=>window.lens.retry($('source-edit').value)));
}
window.onkeydown=e=>{if(e.key==='Escape'&&view!=='main')window.lens.dismiss();};
window.lens.onUpdate(data=>{
  if(data.type==='result'&&view==='result')renderResult(data);
  if(data.type==='drag'&&view==='drag'){const box=$('drag-highlight');Object.assign(box.style,{left:data.x+'px',top:data.y+'px',width:data.width+'px',height:data.height+'px',display:data.width>2&&data.height>2?'block':'none'});}
  if(data.type==='error'&&view==='main')toast(data.error,true);
  if(data.type==='history'&&state&&view==='main'){state.history=data.history;if(tab!=='settings')renderMain();}
});
window.lens.state().then(value=>{state=value;if(view==='select')renderSelect();else if(view==='result')renderResult(state.result);else if(view==='drag')renderDrag();else renderMain();}).catch(error=>{root.textContent='Unable to initialize Lens: '+error.message;});
